library(knitr)
library(rmarkdown)
library(openxlsx)
#getwd()
setwd(paste(getwd(),'/Output',sep=''))
unlink(list.files(pattern='Diagnostics_files'), recursive=TRUE)
setwd('../../R files')
wb <- loadWorkbook(file="../MakeFiles/ModelStructure.xlsx")
fleets <- readWorkbook(wb,sheet='fleetcode')
unlink(list.files(pattern='_cache'), recursive=TRUE)
setwd(paste('../',fls,sep=''))
date <- Sys.time()
fname <- gsub(":",".",gsub("-", "", gsub(" ", "_", paste(date, "Diagnostics.docx", sep='_'))))
fname <- paste(getwd(),'/Output/',fname,sep='')
render(input = "../R files\\Report_v3.Rmd", output_format = "word_document", output_file=fname)
